### ISSUE TITLE
Suport of dimmer and self learning devices

### ISSUE THREAD

**Issue by tml89** [Phunkafizer/node-red-contrib-raspyrfm#1]
In your Shop you describe the support of multiple devices, including dimmer and self learning devices. 
Please support those in NodeRed. 
Regards 
Tim

**Comment by Phunkafizer** [comment]
Latest commit of RaspyRFM enables dim values via API. As of this version a JSON value can be injected to a RaspyRFM node in Node-RED, e.g. 
`{"command": 50}`
